version: "2"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moataz
    volumes:
      - msql-data:/var/lib/mysql
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/chat-app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass moataz
    volumes:
      - redis-data:/data
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
  #   container_name: elasticsearch
  #   restart: always
  #   environment:
  #     - xpack.security.enable=false
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - elasticsearch-data-volume:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:7.4.0
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOST=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
volumes:
  msql-data:
    driver: local
  redis-data:
    driver: local
  # elasticsearch-data-volume:
  #   driver: local
